### ISSUE TITLE
Proposal: Change repo name

### ISSUE THREAD

**Issue by gvn** [MozillaFoundation/mofo-style#25]
I think we should expand the scope to all our code, not just JS.

Possibilities: `mofo-style` (match npm) or `code-style`.

**Comment by simonwex** [comment]
I'd :+1: to match with npm `mofo-style`

**Comment by simonwex** [comment]
Also, I re-filed the request to break this fork: 

![image](https://cloud.githubusercontent.com/assets/25260/12934343/b2d6a140-cf42-11e5-9559-5bd976a78cce.png)

**Comment by gvn** [comment]
I don't seem to have the necessary permissions to change the name. Can you change it @simonwex ?

**Comment by simonwex** [comment]
Done. Could you merge this PR: https://github.com/MozillaFoundation/mofo-style/pull/38
