### ISSUE TITLE
ESlint as a dependency?

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-style#30]
Instead of instructing users to manually run `npm install eslint --save-dev`, does it make sense to add eslint as a devDependency in package.json?

**Comment by gvn** [comment]
I'm not sure I understand the question. That is what that command does. Can you clarify?

**Comment by alanmoo** [comment]
Is there any downside to adding eslint to package.json so that it gets installed automatically when a project requires `mofo-style`?

**Comment by gvn** [comment]
Ohhhhh, I see what you mean. I thought you meant the package.json for the user's project.

Yeah, it seems fine to make ESLint a dependency of mofo-style. Want to make PR?
