### ISSUE TITLE
did we delete the old version?

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-style#39]
id.webmaker.org still depends on the previous version of our styling rules; did we delete the tags for that? id.wmo can't run CI or be deployed with hotfixes without them...

https://travis-ci.org/mozilla/id.webmaker.org/builds/110686445#L825

**Comment by gvn** [comment]
`1.1.0` still appears to be in npm's registry, so it should be ok?

**Comment by gvn** [comment]
Ok to close this?

**Comment by Pomax** [comment]
yeah I'd say so.
